### ISSUE TITLE
Just need working script as .sql file

### ISSUE THREAD

**Issue by DanGerK** [Rochet2/Issues#15]
I got a fully setup server repack and want to add transmogrification.sql to my sql database with HeidiSQL. nothing with compilation. Thank you for sending me this.

**Comment by DanGerK** [comment]
I need a Transmogrification.SQL file to doubleclick and loading it into my already working server repack. Nothing with compile or git or anything. i know how to make a custompatch with DBCutil, CSVed and MPQ Editor. I just need the blank written working transmog.sql file. this method works with any scripot so it must be able to handle a transmogrification.sql script.

**Comment by DanGerK** [comment]
And my friend: I already used google and tutorials. nothing worked on your Transmogrification thing. even not the guide you gave me the last time. i cant get working shit to compile anything. it is the last thing to be needed. like i said it works with a simple script and a custompatch for the client to understand, that there is custom content. i hope i was clear enough and i also hope that you will put more work into this issue then to just send me another tutorial which will dont work in the end.

**Comment by DanGerK** [comment]
and also friends of mine with a bit more experience in this whole scripting thing didnt get it to work on there pc's neither. they tested all that for me and dont want to help me on this topic again.

**Comment by Rochet2** [comment]
You didnt state what the issue was nor post errors etc, need more info.
You cant have transmogrification simply with an SQL file.
My code does not need a client patch. The diff file or patch is used for the server code.
