### ISSUE TITLE
TransmogDisplayVendor.cpp:52:50: fatal error

### ISSUE THREAD

**Issue by jeremymeile** [Rochet2/Issues#16]
build with TrinityCore:
Commit: 3eee1d973033eb362e9d8f26a8b813dd60f0b515 [3eee1d9]
Date: 23 Dec 2014 22:15:30 CET

System: OSX 10.10

http://pastebin.com/XHd6Z77s

**Comment by Rochet2** [comment]
Fix attempt:
https://github.com/Rochet2/TrinityCore/commit/c2de80fe8a86f9ab04d84640ca92d10fba676cd7

Cant test on mac myself

**Comment by Rochet2** [comment]
still waiting for feedback @jeremymeile

**Comment by Rochet2** [comment]
No reply, closing.
