### ISSUE TITLE
TransmogDisplayVendor

### ISSUE THREAD

**Issue by Pro100Hens** [Rochet2/Issues#20]
i test your last rev
TransmogDisplayVendor.
Issue:
- Not save transmog (After Logout/Restart server)
- Not work AllowMixed (All)

**Comment by Rochet2** [comment]
Saving works fine.
Check your player OnSave, OnLogin and OnLogout hooks and their arguments from ScriptMgr.h

Mixed options should now be fine: https://github.com/Rochet2/TrinityCore/commit/8f0362d92d2e29efde7b6555d1cd05c222063eff
