### ISSUE TITLE
Transmog lost after server crash

### ISSUE THREAD

**Issue by fvicaria** [Rochet2/Issues#25]
Every time the server crashes everyone loses their transmog. Everything is still in the DB but for some reason it's not loaded anymore.

I am using Trinitycore 3.3.5 with latest core and DB.

**Comment by Rochet2** [comment]
- Does the core crash often? Can you possibly get a crash log? (compile server in debug)
- Can you check if the items the transmogs are linked to still exist?
- The transmogrifications are selected with a simple SQL query using the player guid. Can you try see if you can select anything from DB with a player's guid from characters table from a character that lost his transmogs?

`SELECT GUID, FakeEntry FROM custom_transmogrification WHERE Owner = 123;`

**Comment by fvicaria** [comment]
The crash is more than likely not related to it.
Yes all seems consistent on the DB, chars exist, they have the items etc.
I can do the query and it will bring me the results as expected.

I can easily reproduce it by close the server abruptly multiple times on my dev machine... Some times when I restart the transmog is there fine. Others it's gone and when it's gone it's gone for good I have to re do it.

I have added the save transmog to the player save routine but it still happens.

Very weird as you said all seem quite simple and the db seem to have all info it needs to re-load the transmog.

I will try to collect more info and get back to you.

**Comment by Rochet2** [comment]
Can you possibly try explain how you shut down the server? Trying to reproduce has not given any results.

Or can you possibly compile in debug mode and try debug the loading process as you are able to reproduce the bug?

Id like to add that this is the first time I have heared of such issue and the code has been in use for years. So its most likely something wrong at your end or with recent TC updates.

**Comment by Rochet2** [comment]
Any update?

**Comment by fvicaria** [comment]
Hi,
It still happens from time to time.
Basically it happens on the live server when it crashes. Not always so very hard to reproduce.
In development I managed to reproduce a couple of times by doing a few transmogs and waiting a few minutes and clicking close on the server console window to simulate a crash.
Most of the times it is OK and the transmog is still there but from time to time it's gone.
I will try again today and get back to you.

Note: the crashes I have sometimes on the live server is in no way related to Transmog.

**Comment by Rochet2** [comment]
Cannot reproduce
