### ISSUE TITLE
ItemGossip/PlayerGossip

### ISSUE THREAD

**Issue by TankstaS** [Rochet2/Issues#26]
Hello Rochet2.

I was wondering if your Item/PlayerGossip is available for WoW version 4.0.6?
I have been trying to add it without any success and would like to know if its just because its not viable or that I'm doing something awfully wrong.

Thanks in advance,

Tanksta

**Comment by Rochet2** [comment]
its possible in 4.3.4 at least so most likely 4.0.6 can be done as well.

**Comment by Rochet2** [comment]
Did you succeed in making it or did you give up on it?

**Comment by TankstaS** [comment]
I have given up on it I've tried multiple methods of applying and it has not worked for me yet

**Comment by Rochet2** [comment]
The patch is now available for 3.3.5 and 6.x TC. I will not be supporting other sources at this time.
