### ISSUE TITLE
Transmog binding

### ISSUE THREAD

**Issue by Rochet2** [Rochet2/Issues#28]
Reported by Demonid?

> http://puu.sh/kFnDw/da19656104.jpg
> http://puu.sh/kFnEV/61d112269a.jpg
> http://puu.sh/kFnHz/daf20941fe.jpg
> First image i show the item unbinded
> 2nd image i just transmog that item and it's binded
> Third image is after loging out and in, items it's unbinded
> 
> At that because
> on the first image
> I had the default item without transmog
> on the 2nd image i did the transmog
> that why it changed and got "binded"
> until i relog
> Btw at the end i still had the transmog visual but the item unbinded
> http://puu.sh/kFo0m/374523b13e.jpg

![da19656104](https://cloud.githubusercontent.com/assets/468816/10800266/b55d6b04-7db9-11e5-9706-864016fb666d.jpg)
![61d112269a](https://cloud.githubusercontent.com/assets/468816/10800267/b5610f66-7db9-11e5-99b4-9753bfbf6ab3.jpg)
![daf20941fe](https://cloud.githubusercontent.com/assets/468816/10800268/b5613be4-7db9-11e5-99bc-b34a79911966.jpg)
![374523b13e](https://cloud.githubusercontent.com/assets/468816/10800269/b562c9a0-7db9-11e5-9abc-143247bc2c69.jpg)

**Comment by ryoting** [comment]
bug is solved?

**Comment by Rochet2** [comment]
Could not reproduce on latest version.
