### ISSUE TITLE
hello rochet,can you release a trinitycore`s multi trainer script?

### ISSUE THREAD

**Issue by ryoting** [Rochet2/Issues#32]
i found AlexeWarr`s this, but no download anywhere.

thanks

**Comment by Rochet2** [comment]
Hmm, Ill think about it :)

**Comment by ryoting** [comment]
thank you very much

**Comment by ryoting** [comment]
thank you very much,waiting for you. :)
btw,it`s the 335a rev  latest OF TC

**Comment by Rochet2** [comment]
https://github.com/Rochet2/TrinityCore/blob/multitrainer/src/server/scripts/Custom/multitrainer/README.md
Not yet in website, but already posted on github.
