### ISSUE TITLE
Compiling issue's getting error's on most off your work.

### ISSUE THREAD

**Issue by Saurfang91** [Rochet2/Issues#33]
Hello Rochet!

i have been trying a few days now with no luck, tryed reforger - transmoger but seems like i get a lot off error's when trying to compile them.

`2>D:\WoW Server Stuff\Trinity 3.3.5a Core\Trinity\src\server\scripts\Custom\custom_script_loader.cpp(20): fatal error C1020: unexpected #endif
3>------ Build started: Project: worldserver, Configuration: Release Win32 ------
3>scripts.lib(custom_script_loader.obj) : error LNK2019: unresolved external symbol "void __cdecl AddSC_NPC_TransmogDisplayVendor(void)" (?AddSC_NPC_TransmogDisplayVendor@@YAXXZ) referenced in function "void __cdecl AddCustomScripts(void)" (?AddCustomScripts@@YAXXZ)
3>scripts.lib(spell_generic.obj) : error LNK2019: unresolved external symbol "public: static unsigned int __cdecl TransmogDisplayVendorMgr::GetFakeEntry(class Item const *)" (?GetFakeEntry@TransmogDisplayVendorMgr@@SAIPBVItem@@@Z) referenced in function "private: void __thiscall spell_gen_clone_weapon_aura::spell_gen_clone_weapon_auraScript::OnApply(class AuraEffect const *,enum AuraEffectHandleModes)" (?OnApply@spell_gen_clone_weapon_auraScript@spell_gen_clone_weapon_aura@@AAEXPBVAuraEffect@@W4AuraEffectHandleModes@@@Z)
3>game.lib(Player.obj) : error LNK2001: unresolved external symbol "public: static unsigned int __cdecl TransmogDisplayVendorMgr::GetFakeEntry(class Item const *)" (?GetFakeEntry@TransmogDisplayVendorMgr@@SAIPBVItem@@@Z)
3>game.lib(SpellHandler.obj) : error LNK2001: unresolved external symbol "public: static unsigned int __cdecl TransmogDisplayVendorMgr::GetFakeEntry(class Item const *)" (?GetFakeEntry@TransmogDisplayVendorMgr@@SAIPBVItem@@@Z)
3>game.lib(Player.obj) : error LNK2019: unresolved external symbol "public: static void __cdecl TransmogDisplayVendorMgr::HandleTransmogrify(class Player *,class Creature *,unsigned int,unsigned int,bool)" (?HandleTransmogrify@TransmogDisplayVendorMgr@@SAXPAVPlayer@@PAVCreature@@II_N@Z) referenced in function __catch$?BuyItemFromVendorSlot@Player@@QAE_NVObjectGuid@@IIEEE@Z$0
3>game.lib(Player.obj) : error LNK2019: unresolved external symbol "public: static void __cdecl TransmogDisplayVendorMgr::DeleteFakeEntry(class Player *,class Item *)" (?DeleteFakeEntry@TransmogDisplayVendorMgr@@SAXPAVPlayer@@PAVItem@@@Z) referenced in function "public: void __thiscall Player::MoveItemFromInventory(unsigned char,unsigned char,bool)" (?MoveItemFromInventory@Player@@QAEXEE_N@Z)
3>D:\WoW Server Stuff\Trinity 3.3.5a Core\Build\bin\Release\worldserver.exe : fatal error LNK1120: 4 unresolved externals
========== Build: 1 succeeded, 2 failed, 19 up-to-date, 0 skipped ==========`

this is what i get with the TransmogDiplayVendor. i also used the .diff, followed the guide you made but seems its no luck. tryed to get new core and build a few times but still no luck... im running the 3.3.5a 335.60 core, would be realy happy if you can guide me true how to fix this :)

**Comment by Rochet2** [comment]
Well, cant say much about this based on these errors only.
But obviously something is wrong in your custom_script_loader.cpp
and you may be using an old diff or a new diff on old source. Or possibly I need to update my work for newest TC as their commits may have broken it.

Can you send the diff you used and the TC version you use?

**Comment by Saurfang91** [comment]
here is the following .diff and the TC i use is the 3.3.5 branch  TDB 6.03. latest core.

i have never added a script or diff expect the Multivendor you made and that worked great. only thing i wondering about is if i have to use Cmake first to generate it and then do the compiling in the VisualStudio after? (i am using the VS 2015)

Just downloaded and failed same error.
[http://www.mediafire.com/download/4uadqy5kq42t8da/reforging.diff](url)

**Comment by Rochet2** [comment]
Yes, you should always run cmake when you add/remove files from source - and the diff adds files.

**Comment by Saurfang91** [comment]
ah okey maybe try that first then :P il post report back here when done :)

**Comment by Saurfang91** [comment]
just asking quick here is it possible to do more then one at a time?

**Comment by Rochet2** [comment]
More than one what at a time?

**Comment by Saurfang91** [comment]
if i whant more then one .cpp or diff can i do more at a time? or just do one and one with cmake and compiling? and btw that worked like a charm didint know i had to use Cmake first then VS after :D

**Comment by Saurfang91** [comment]
i get this error when trying to apply the Transmoger:

$ git apply transmogvendor.diff
error: patch failed: src/server/game/Entities/Player/Player.cpp:12205
error: src/server/game/Entities/Player/Player.cpp: patch does not apply
error: patch failed: src/server/game/Entities/Player/Player.h:2267
error: src/server/game/Entities/Player/Player.h: patch does not apply
error: patch failed: src/server/scripts/Custom/custom_script_loader.cpp:16
error: src/server/scripts/Custom/custom_script_loader.cpp: patch does not apply

anything i can do to fix this? :S

**Comment by Saurfang91** [comment]
Worked with direct merge instead :) thnx for you help :)
