### ISSUE TITLE
Death knight and Cultist skins

### ISSUE THREAD

**Issue by Dranos-Nupper** [Rochet2/Issues#35]
I attempt to add them but it reverts to a normal skin.
14 SKin
1 Face
human female

**Comment by Rochet2** [comment]
did you use the deathknight class for the DK face?/skin?
And which is which?
Is both face and skin supposed to be for DK and for cultist?
Or face is for DK and skin is for cultist? or what?

**Comment by Rochet2** [comment]
Death knight skins need class set to death knight class. The class can be set in the dress NPCs DB table now.
Cultist skins require client editing to show, so its not possible to show them through dressnpcs alone and thus its not a bug / cant do anything.
