### ISSUE TITLE
Portal Master - Some options missing from menu

### ISSUE THREAD

**Issue by StygianTheBest** [Rochet2/Issues#36]
These options are missing in the menu for me using a level 80 Horde toon. Appears they are for Alliance only characters, but I think either faction should be able to go to these dungeons and vice/versa for any others.

>(@GOSSIP_MENU+1, 0, 2, "Gnomeregan", 1, 1, 0, 0, 0, 0, "Are you sure, that you want to go to Gnomeregan?"),
(@GOSSIP_MENU+1, 1, 2, "The Deadmines", 1, 1, 0, 0, 0, 0, "Are you sure, that you want to go to The Deadmines?"),
(@GOSSIP_MENU+1, 2, 2, "The Stockade", 1, 1, 0, 0, 0, 0, "Are you sure, that you want to go to The Stockade?"),

**Comment by Rochet2** [comment]
you are horde and those are alliance areas.
blocked for that reason.
remove the conditions from conditions table if you dont like it.

**Comment by StygianTheBest** [comment]
Will do. Didn't realize those were conditional at first. Thanks for the effort put into this. 👍
